# PyTorch Tensors

- This tutorial briefly describes some basic operations on Tensors in PyTorch. 
- This [documentation](http://pytorch.org/docs/master/torch.html) from pytorch contains information about all the possible operations on Tensors.

In [1]:
import torch
import torch.nn as nn
import numpy as np

## Getting started with Tensors

### Creating a Tensor

In [2]:
#Create Torch Tensor from a list
x = torch.Tensor([[1,2,3],[4,5,6]])
print (x) # prints the tensor
print ('shape: ',x.shape) # returns the shape of the tensor. You can also use x.size()

tensor([[1., 2., 3.],
        [4., 5., 6.]])
shape:  torch.Size([2, 3])


- you can use the `.numpy()` function to obtain the numpy array from tensor.

In [3]:
print ('numpy array: ')
print (x.numpy()) # obtains the numpy array from the pytorch Tensor

numpy array: 
[[1. 2. 3.]
 [4. 5. 6.]]


- The default `torch.Tensor` is a float tensor as you can see above.
- You can use `torch.LongTensor` for tensor of integer types.

In [4]:
x = torch.LongTensor([1,4,6])
print (x) # prints the tensor
print ('shape: ', x.shape) # returns the shape of the tensor. You can also use x.size()
print ('numpy array: ',x.numpy()) #obtains the numpy array

tensor([1, 4, 6])
shape:  torch.Size([3])
numpy array:  [1 4 6]


- You can also create Tensors from numpy arrays

In [5]:
one_arr = np.ones(5) # a numpy array
print (one_arr)

[1. 1. 1. 1. 1.]


In [6]:
x = torch.from_numpy(one_arr)
print (x) 
print (x.shape) #obtains the shape of the tensor

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
torch.Size([5])


In [7]:
print (x.numpy()) #obtains the numpy array from the Tensor

[1. 1. 1. 1. 1.]


### Indexing into a Tensor

In [8]:
a = np.random.rand(3,4,5)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)

tensor([[[0.8682, 0.8696, 0.5135, 0.7248, 0.6488],
         [0.7342, 0.9033, 0.0143, 0.8496, 0.3042],
         [0.2960, 0.2531, 0.8331, 0.2814, 0.0978],
         [0.0321, 0.6485, 0.4407, 0.3596, 0.3957]],

        [[0.3244, 0.2310, 0.4582, 0.1912, 0.6120],
         [0.1808, 0.7932, 0.2588, 0.5766, 0.0070],
         [0.8960, 0.7016, 0.0391, 0.0090, 0.6158],
         [0.4305, 0.7438, 0.0708, 0.6067, 0.9001]],

        [[0.4170, 0.4952, 0.5016, 0.6365, 0.4198],
         [0.6025, 0.1150, 0.6651, 0.4874, 0.9540],
         [0.3470, 0.4095, 0.9542, 0.6403, 0.0175],
         [0.1135, 0.8187, 0.1936, 0.0107, 0.6268]]], dtype=torch.float64)
shape:  torch.Size([3, 4, 5])


In [9]:
# you can index into them like arrays
print (x[0]) #gives you a matrix Tensor
print (x[0].shape)

tensor([[0.8682, 0.8696, 0.5135, 0.7248, 0.6488],
        [0.7342, 0.9033, 0.0143, 0.8496, 0.3042],
        [0.2960, 0.2531, 0.8331, 0.2814, 0.0978],
        [0.0321, 0.6485, 0.4407, 0.3596, 0.3957]], dtype=torch.float64)
torch.Size([4, 5])


In [10]:
# you can index into them like arrays
print (x[0][2]) # gives you a vector Tensor
print (x[0][2].shape)

tensor([0.2960, 0.2531, 0.8331, 0.2814, 0.0978], dtype=torch.float64)
torch.Size([5])


In [11]:
print (x[0][2][3].item()) #this gives you a scalar Python number

0.2813508452768917


### Reshaping a Tensor

- To reshape a tensor to a different size, you can use the `.view()` function. 
- The `.view()` function returns a tensor with the same data as the self tensor but of a different size

In [12]:
a = np.random.rand(2,6)
x = torch.from_numpy(a)
print (x)
print ('shape: ',x.shape)

tensor([[0.1230, 0.5631, 0.7485, 0.1059, 0.8521, 0.1374],
        [0.6063, 0.8017, 0.8821, 0.5820, 0.8318, 0.9742]], dtype=torch.float64)
shape:  torch.Size([2, 6])


In [13]:
y = x.view(3,4) #reshapes it into a tensor of size 3 x 4
print (y)
print (y.shape)

tensor([[0.1230, 0.5631, 0.7485, 0.1059],
        [0.8521, 0.1374, 0.6063, 0.8017],
        [0.8821, 0.5820, 0.8318, 0.9742]], dtype=torch.float64)
torch.Size([3, 4])


In [14]:
y = x.view(2,3,2) #reshapes the tensor into 2 x 3 x 2
print (y)
print (y.shape)

tensor([[[0.1230, 0.5631],
         [0.7485, 0.1059],
         [0.8521, 0.1374]],

        [[0.6063, 0.8017],
         [0.8821, 0.5820],
         [0.8318, 0.9742]]], dtype=torch.float64)
torch.Size([2, 3, 2])


- if one of the dimensions is `-1`, as shown below, then its size can be inferred. So, you cannot have multiple -1's in view.

In [15]:
y = x.view(4,3) #reshapes the tensor into 4x3
print (y)
print (y.shape)

tensor([[0.1230, 0.5631, 0.7485],
        [0.1059, 0.8521, 0.1374],
        [0.6063, 0.8017, 0.8821],
        [0.5820, 0.8318, 0.9742]], dtype=torch.float64)
torch.Size([4, 3])


In [16]:
y = x.view(4,-1) #same as above, but the second dimension can be inferred.
print (y)
print (y.shape)

tensor([[0.1230, 0.5631, 0.7485],
        [0.1059, 0.8521, 0.1374],
        [0.6063, 0.8017, 0.8821],
        [0.5820, 0.8318, 0.9742]], dtype=torch.float64)
torch.Size([4, 3])


### Operations on Tensors

- You can do some basic operations on tensors like arrays

In [17]:
a = np.random.rand(1,5)
x = torch.from_numpy(a)
print (x)
print (x.shape)

tensor([[0.7132, 0.5945, 0.7317, 0.6542, 0.7698]], dtype=torch.float64)
torch.Size([1, 5])


In [18]:
b = np.ones((1,5))
y = torch.from_numpy(b)
print (y)
print (y.shape)

tensor([[1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([1, 5])


In [19]:
print (x + y) #element wise addition

tensor([[1.7132, 1.5945, 1.7317, 1.6542, 1.7698]], dtype=torch.float64)


In [20]:
print (x - y) #element wise subtraction

tensor([[-0.2868, -0.4055, -0.2683, -0.3458, -0.2302]], dtype=torch.float64)


In [21]:
print (x * y)  #element wise multiplication

tensor([[0.7132, 0.5945, 0.7317, 0.6542, 0.7698]], dtype=torch.float64)


- Another useful operation on tensors is concatenation.
- You can use the `torch.cat()` function, it takes in a list/sequence of tensors and concatenates them

In [22]:
torch.cat([x,y]) # concatenates them along the row (dim=0) by default.

tensor([[0.7132, 0.5945, 0.7317, 0.6542, 0.7698],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], dtype=torch.float64)

In [23]:
torch.cat([x,y], dim=1) # concatenates them along the column when dim=1 is mentioned.

tensor([[0.7132, 0.5945, 0.7317, 0.6542, 0.7698, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]], dtype=torch.float64)

- If you want to expand a Tensor along the singleton dimension, you can use the `.expand()` function.

In [24]:
x = torch.Tensor([[1],[2],[3]])
print (x)
print (x.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [25]:
x.expand(3,4) #expands it along the second dimension from (3 x 1) to be (3 x 4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [26]:
x = torch.Tensor([5,6]).view(-1,2) #reshaping it to 1 x 2
x.expand(5,2) #expands it along the first dimension from (1 x 2) to (5 x 2)

tensor([[5., 6.],
        [5., 6.],
        [5., 6.],
        [5., 6.],
        [5., 6.]])

- These are the basic operations on the Tensors that will be very useful. You can check the [documentation here](http://pytorch.org/docs/master/torch.html) for all list of operations.